export const longText = {
  de: {
    title: 'Die Geschichte von ZARA ',
    text:
      'Man stelle sich vor: Vor dem November 1999 gab es noch kein ZARA! Es gab keine Anlaufstelle für Zeug*innen und direkt Betroffene von Rassismus. Zuvor hatte es schon eine „Anti-Rassismus-Hotline“, vom Verein Helping Hands betrieben, gegeben. Diese war aber Geldmangels wegen schon wieder eingestellt worden.<br /><br />Eine knappe Handvoll Jungakademiker*innen, die eigentlich ursprünglich alle ganz etwas anderes machen wollten, haben es nicht ertragen, dass es in Österreich so gar keine direkte Beratungsstelle gegen Rassismus geben sollte und kurzerhand – ohne Mittel und Struktur – aus der puren Erkenntnis der Notwendigkeit heraus, den Verein ZARA ins Leben gerufen.<br /><br />Zivilcourage sollte erforscht und gelebt werden, - Menschen die mit konkreten rassistischen Vorfällen konfrontiert sind, sollten eine kompetente Anlaufstelle haben, die vor allem juristische Hilfestellung bietet. Wichtig war auch von Anbeginn, die gemeldeten Vorfälle systematisch zu dokumentieren und darzustellen. Der jährliche Rassismus Report war geboren – die einzige regelmäßige bundesweite qualitative Datenquelle zu Alltagsrassismus in Österreich.<br /><br />Die Anfänge des Angebotes waren bescheiden, aber von großer Solidarität getragen. Ein Arbeitsplatz und ein Telefon in den Räumlichkeiten des Vereins SOS Mitmensch musste reichen, um die Beratungsstelle zu unterhalten.<br /><br />Mit Hilfe der Stadt Wien und privaten Unterstützer*innen konnte ein paar Jahre später ein Souterrainlokal zum ZARA-Hauptquartier umgebaut werden. Ein erstes großes EU-Projekt brachte auch internationale Anerkennung. Bald schon war klar, dass es neben der „nachsorgenden“ Arbeit der Beratung auch notwendig war, präventiv und sensibilisierend zu wirken. Es wurden Zivilcourage- Argumentations- und Antidiskriminierungstrainings entwickelt und angeboten. Training und Öffentlichkeitsarbeit wurden immer wichtigere Säulen der Arbeit von ZARA.<br /><br />Eine Übersiedlung in das heutige ZARA-Büro brachte ab 2006 mehr Licht und Sicherheit für die Mitarbeiter*innen und weitere Professionalisierung. Im Jahr 2017 kam noch ein wichtiger Schwerpunkt hinzu, der sich schon einige Jahre lang abgezeichnet hatte: ZARA beschäftigt sich ganz intensiv mit dem Phänomen „Hass im Netz“ und betreibt nun auch eine Melde- und Beratungsstelle dazu. In nunmehr fast 20 Jahren ist es gelungen, nicht nur das Angebot der Beratung aufrecht zu erhalten, sondern auch im präventiven Sektor und in der Arbeit mit strukturellen Diskriminierungen aktiv zu bleiben.<br /><br />Immer haben sich zur richtigen Zeit, die richtigen Themenstellungen, die richtigen Menschen bei ZARA getroffen. Es ist diese Mischung, die unser Engagement antreibt und weiterbringt.'
  },
  en: {
    text:
      'Man stelle sich vor: Vor dem November 1999 gab es noch kein ZARA! Es gab keine Anlaufstelle für Zeug*innen und direkt Betroffene von Rassismus. Zuvor hatte es schon eine „Anti-Rassismus-Hotline“, vom Verein Helping Hands betrieben, gegeben. Diese war aber Geldmangels wegen schon wieder eingestellt worden.<br /><br />Eine knappe Handvoll Jungakademiker*innen, die eigentlich ursprünglich alle ganz etwas anderes machen wollten, haben es nicht ertragen, dass es in Österreich so gar keine direkte Beratungsstelle gegen Rassismus geben sollte und kurzerhand – ohne Mittel und Struktur – aus der puren Erkenntnis der Notwendigkeit heraus, den Verein ZARA ins Leben gerufen.<br /><br />Zivilcourage sollte erforscht und gelebt werden, - Menschen die mit konkreten rassistischen Vorfällen konfrontiert sind, sollten eine kompetente Anlaufstelle haben, die vor allem juristische Hilfestellung bietet. Wichtig war auch von Anbeginn, die gemeldeten Vorfälle systematisch zu dokumentieren und darzustellen. Der jährliche Rassismus Report war geboren – die einzige regelmäßige bundesweite qualitative Datenquelle zu Alltagsrassismus in Österreich.<br /><br />Die Anfänge des Angebotes waren bescheiden, aber von großer Solidarität getragen. Ein Arbeitsplatz und ein Telefon in den Räumlichkeiten des Vereins SOS Mitmensch musste reichen, um die Beratungsstelle zu unterhalten.<br /><br />Mit Hilfe der Stadt Wien und privaten Unterstützer*innen konnte ein paar Jahre später ein Souterrainlokal zum ZARA-Hauptquartier umgebaut werden. Ein erstes großes EU-Projekt brachte auch internationale Anerkennung. Bald schon war klar, dass es neben der „nachsorgenden“ Arbeit der Beratung auch notwendig war, präventiv und sensibilisierend zu wirken. Es wurden Zivilcourage- Argumentations- und Antidiskriminierungstrainings entwickelt und angeboten. Training und Öffentlichkeitsarbeit wurden immer wichtigere Säulen der Arbeit von ZARA.<br /><br />Eine Übersiedlung in das heutige ZARA-Büro brachte ab 2006 mehr Licht und Sicherheit für die Mitarbeiter*innen und weitere Professionalisierung. Im Jahr 2017 kam noch ein wichtiger Schwerpunkt hinzu, der sich schon einige Jahre lang abgezeichnet hatte: ZARA beschäftigt sich ganz intensiv mit dem Phänomen „Hass im Netz“ und betreibt nun auch eine Melde- und Beratungsstelle dazu. In nunmehr fast 20 Jahren ist es gelungen, nicht nur das Angebot der Beratung aufrecht zu erhalten, sondern auch im präventiven Sektor und in der Arbeit mit strukturellen Diskriminierungen aktiv zu bleiben.<br /><br />Immer haben sich zur richtigen Zeit, die richtigen Themenstellungen, die richtigen Menschen bei ZARA getroffen. Es ist diese Mischung, die unser Engagement antreibt und weiterbringt.'
  }
}
