export const longText = {
  de: {
    title: 'ZARA Impressum',
    text:
      'Die Informationen auf zara.or.at werden zur Verfügung gestellt von:<br /><br />ZARA-Zivilcourage und Anti-Rassismus-Arbeit<br />Schönbrunner Straße 119/13, 1050 Wien<br />+43 (0) 1 929 13 99<br /><a href="mailto:office@zara.or.at">office@zara.or.at</a><br /><br />Für den Inhalt verantwortlich: ZARA – Zivilcourage und Anti-Rassismus-Arbeit<br />Redaktion: Philippe Schennach, Dieter Schindlauer, Caroline Kerschbaumer, Cäcilia Kappel, Anna-Laura Schreilechner und das gesamte ZARA Team<br /><br />Web Design und Corporate Design: Fabian Lang (<a href="http://www.dergestalt.at">www.dergestalt.at</a>)<br />Web Development: Emanuel Donner (<a href="http://seriouspigeon.at">seriouspigeon.at</a>)<br />Web Design und Konzeption: Christoph Autengruber (<a href="http://www.sidekick-ux.com">www.sidekick-ux.com</a>)<br /><br />Rechtsform: Verein (ZVR-Zahl: 236017119 / DVR: 2110769)<br />Uni Credit Bank Austria BLZ 12000 | Kto: 05211362800IBAN: AT25 1100 0052 1136 2800BIC: BKAUATWW<br />ZARA wird gefördert von der MA 17<br /><br />Sämtliche auf der Website www.zara.or.at veröffentlichten Texte, Abbildungen, Grafiken, Videosequenzen, Tondokumente und andere Materialien unterliegen dem Schutz des Urheberrechts. Urheber*in ist entweder ZARA oder die in der Quellenangabe genannte Person oder Institution. Eine Wiedergabe, Massenvervielfältigung oder Veröffentlichung der auf der Website befindlichen Informationen ist nicht gestattet. Die Genehmigung zum Abdruck oder zur Weiterverbreitung kann im Einzelfall erteilt werden.'
  },
  en: {
    text:
      'Die Informationen auf zara.or.at werden zur Verfügung gestellt von:<br /><br />ZARA-Zivilcourage und Anti-Rassismus-Arbeit<br />Schönbrunner Straße 119/13, 1050 Wien<br />+43 (0) 1 929 13 99<br /><a href="mailto:office@zara.or.at">office@zara.or.at</a><br /><br />Für den Inhalt verantwortlich: ZARA – Zivilcourage und Anti-Rassismus-Arbeit<br />Redaktion: Philippe Schennach, Dieter Schindlauer, Caroline Kerschbaumer, Cäcilia Kappel, Anna-Laura Schreilechner und das gesamte ZARA Team<br /><br />Web Design und Corporate Design: Fabian Lang (<a href="http://www.dergestalt.at">www.dergestalt.at</a>)<br />Web Development: Emanuel Donner (<a href="http://seriouspigeon.at">seriouspigeon.at</a>)<br />Web Design und Konzeption: Christoph Autengruber (<a href="http://www.sidekick-ux.com">www.sidekick-ux.com</a>)<br /><br />Rechtsform: Verein (ZVR-Zahl: 236017119 / DVR: 2110769)<br />Uni Credit Bank Austria BLZ 12000 | Kto: 05211362800IBAN: AT25 1100 0052 1136 2800BIC: BKAUATWW<br />ZARA wird gefördert von der MA 17<br /><br />Sämtliche auf der Website www.zara.or.at veröffentlichten Texte, Abbildungen, Grafiken, Videosequenzen, Tondokumente und andere Materialien unterliegen dem Schutz des Urheberrechts. Urheber*in ist entweder ZARA oder die in der Quellenangabe genannte Person oder Institution. Eine Wiedergabe, Massenvervielfältigung oder Veröffentlichung der auf der Website befindlichen Informationen ist nicht gestattet. Die Genehmigung zum Abdruck oder zur Weiterverbreitung kann im Einzelfall erteilt werden.'
  }
}
