export const longText = {
  de: {
    title: 'Sende uns eine verschlüsselte Email',
    text:
      '<p>Bei besonders sensiblen Vorfällen oder wenn Du uns Daten zuschicken möchtest, die einen besonders hohen Anspruch auf Datensicherheit haben, kannst Du uns auch eine E-Mail mit PGP-Verschlüsselung zusenden. In manchen Situationen kann es angebracht sein, bei einem digitalen Schriftverkehr eine zusätzliche Sicherheitsebene. </p><p>Das Verschlüsseln des Inhalts einer E-Mail mit öffentlichen Schlüsseln ist eine gute Möglichkeit, den Inhalt der Email nicht zu gefährden. Durch die Verschlüsselung von E-Mails und Dokumenten kann auch verhindert werden, dass unautorisierte Dritte den Inhalt einer Konversation lesen. Diese Seite enthält den öffentlichen Schlüssel für ZARA-Beratung. </p><p>Um eine verschlüsselte Nachricht an die Beratungsstellen zu senden, musst Du einen eigenen Schlüssel erstellen und die Nachricht anschließend sowohl mit Deinem Schlüsseln als auch mit dem öffentlichen Schlüssel von ZARA-Beratung verschlüsseln. Es gibt viele verschiedene Implementierungen der Kryptographie mit öffentlichen Schlüsseln. Bei ZARA haben wir uns für eine Open Source-Implementierung des OpenPGP-Standards entschieden. </p><p>Wie bei jeder Kryptografieimplementierung mit einem öffentlichen Schlüssel kann es zu Inkompatibilitäten kommen. Wir werden unser Bestes tun, um Unstimmigkeiten zu beheben, aber einige Probleme können außerhalb unserer technischen Möglichkeiten liegen. Sollest Du von uns keine Rückmeldung bekommen, versuche uns bitte telefonisch zu erreichen: +43 (1) 929 13 99</p>'
  },
  en: {
    title: 'Sende uns eine verschlüsselte Email',
    text:
      '<p>Bei besonders sensiblen Vorfällen oder wenn Du uns Daten zuschicken möchtest, die einen besonders hohen Anspruch auf Datensicherheit haben, kannst Du uns auch eine E-Mail mit PGP-Verschlüsselung zusenden. In manchen Situationen kann es angebracht sein, bei einem digitalen Schriftverkehr eine zusätzliche Sicherheitsebene. </p><p>Das Verschlüsseln des Inhalts einer E-Mail mit öffentlichen Schlüsseln ist eine gute Möglichkeit, den Inhalt der Email nicht zu gefährden. Durch die Verschlüsselung von E-Mails und Dokumenten kann auch verhindert werden, dass unautorisierte Dritte den Inhalt einer Konversation lesen. Diese Seite enthält den öffentlichen Schlüssel für ZARA-Beratung. </p><p>Um eine verschlüsselte Nachricht an die Beratungsstellen zu senden, musst Du einen eigenen Schlüssel erstellen und die Nachricht anschließend sowohl mit Deinem Schlüsseln als auch mit dem öffentlichen Schlüssel von ZARA-Beratung verschlüsseln. Es gibt viele verschiedene Implementierungen der Kryptographie mit öffentlichen Schlüsseln. Bei ZARA haben wir uns für eine Open Source-Implementierung des OpenPGP-Standards entschieden. </p><p>Wie bei jeder Kryptografieimplementierung mit einem öffentlichen Schlüssel kann es zu Inkompatibilitäten kommen. Wir werden unser Bestes tun, um Unstimmigkeiten zu beheben, aber einige Probleme können außerhalb unserer technischen Möglichkeiten liegen. Sollest Du von uns keine Rückmeldung bekommen, versuche uns bitte telefonisch zu erreichen: +43 (1) 929 13 99</p>'
  }
}
