export const longText = {
  de: {
    title: 'Senden Sie uns eine verschlüsselte Email',
    text:
      '<p>Bei besonders sensiblen Vorfällen, zu denen Sie uns Daten schicken möchten, die einen besonders hohen Anspruch auf Datensicherheit haben, können Sie uns auch eine Email mit PGP-Verschlüsselung zusenden. In manchen Situationen kann es angebracht sein, bei einem digitalen Schriftverkehr eine zusätzliche Sicherheitsebene einzufügen.<br><br>Durch die Verschlüsselung von Emails und Dokumenten kann verhindert werden, dass unautorisierte Dritte den Inhalt einer Konversation mitlesen. Um eine verschlüsselte Nachricht an die ZARA Beratungsstellen zu senden, müssen Sie einen eigenen Schlüssel erstellen und die Nachricht anschließend sowohl mit Ihrem eigenen Schlüssel als auch mit dem öffentlichen Schlüssel von ZARA-Beratung, verschlüsseln. Es gibt viele verschiedene Möglichkeiten Kryptografie mit öffentlichen Schlüsseln zu implementieren. Bei ZARA haben wir uns für eine Open Source-Implementierung des OpenPGP-Standards entschieden.<br><br>Bei der Implementierung einer Kryptografie mit einem öffentlichen Schlüssel, können Inkompatibilitäten auftauchen. Wir werden unser Bestes tun, um Unstimmigkeiten zu beheben, aber einige Probleme können außerhalb unserer technischen Möglichkeiten liegen. Sollten Sie von uns keine Rückmeldung erhalten, versuchen Sie uns bitte telefonisch zu erreichen: +43 (0) 1 929 13 99</p>'
  },
  en: {
    title: 'Senden Sie uns eine verschlüsselte Email',
    text:
      '<p>Bei besonders sensiblen Vorfällen, zu denen Sie uns Daten schicken möchten, die einen besonders hohen Anspruch auf Datensicherheit haben, können Sie uns auch eine Email mit PGP-Verschlüsselung zusenden. In manchen Situationen kann es angebracht sein, bei einem digitalen Schriftverkehr eine zusätzliche Sicherheitsebene einzufügen.<br><br>Durch die Verschlüsselung von Emails und Dokumenten kann verhindert werden, dass unautorisierte Dritte den Inhalt einer Konversation mitlesen. Um eine verschlüsselte Nachricht an die ZARA Beratungsstellen zu senden, müssen Sie einen eigenen Schlüssel erstellen und die Nachricht anschließend sowohl mit Ihrem eigenen Schlüssel als auch mit dem öffentlichen Schlüssel von ZARA-Beratung, verschlüsseln. Es gibt viele verschiedene Möglichkeiten Kryptografie mit öffentlichen Schlüsseln zu implementieren. Bei ZARA haben wir uns für eine Open Source-Implementierung des OpenPGP-Standards entschieden.<br><br>Bei der Implementierung einer Kryptografie mit einem öffentlichen Schlüssel, können Inkompatibilitäten auftauchen. Wir werden unser Bestes tun, um Unstimmigkeiten zu beheben, aber einige Probleme können außerhalb unserer technischen Möglichkeiten liegen. Sollten Sie von uns keine Rückmeldung erhalten, versuchen Sie uns bitte telefonisch zu erreichen: +43 (0) 1 929 13 99</p>'
  }
}
